CREATE TABLE groups
(
    id int PRIMARY KEY AUTO_INCREMENT,
    display_name varchar(191) NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);